name: DocsQA Trigger

on:
  push:
    branches:
      - master
    paths:
      - 'docs/**'
      
jobs:
  trigger-docsqa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: deepankarm/sample-action@main
        with:
          repo: deepankarm/_jina
          token: ${{ secrets.ACCESS_TOKEN }}
