name: Deploy docs to Netlify

on:
  workflow_dispatch:
    inputs:
      branch:
        required: true
        default: master

jobs:
  deploy:
    name: Deploy to Netlify
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "BRANCH_NAME=${{ github.event.inputs.branch }}" >> $GITHUB_ENV
      - uses: actions/checkout@v2
        with:
          repository: jina-ai/jina
          ref: ${{ env.BRANCH_NAME }}
      - uses: actions/setup-python@v2
      - run: |
          python -m pip install --upgrade pip
      - uses: jsmrcaga/action-netlify-deploy
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          build_directory: docs/_build/dirhtml
          install_command: pip install -r docs/requirements.txt
          build_command: bash ./docs/makedocs.sh
          deploy_alias: ${{ env.BRANCH_NAME }}
      - name: Status check
        uses: Sibz/github-status-action@v1.1.1
        with:
          authToken: ${{ secrets.GITHUB_TOKEN }}
          context: Netlify preview
          state: success
          target_url: https://${{ env.BRANCH_NAME }}--my-site.netlify.app
          
