name: Deploy docs to Netlify

on:
  workflow_dispatch:
    inputs:
      branch:
        required: true
        default: master

jobs:
  deploy:
    name: Deploy to Netlify
    steps:
      - uses: actions/checkout@v2
        with:
          repository: jina-ai/jina
          ref: ${{ github.event.inputs.branch }}
      - uses: actions/setup-python@v2
      - run: |
          python -m pip install --upgrade pip
      - uses: jsmrcaga/action-netlify-deploy@v1.1.0
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          build_directory: docs/_build/dirhtml
          install_command: pip install -r docs/requirements.txt
          build_command: bash ./docs/makedocs.sh
          
