name: Manual Docs Build (Staging)

on:
  workflow_dispatch:
    inputs:
      release_token:
        description: 'Your release token'
        required: true
      triggered_by:
        description: 'CD | TAG | MANUAL'
        required: false
        default: MANUAL

jobs:
  token-check:
    runs-on: ubuntu-latest
    steps:
      - run: echo "success!"
        if: "${{ github.event.inputs.release_token }} == ${{ env.release_token }}"
        env:
          release_token: ${{ secrets.JINA_CORE_RELEASE_TOKEN }}

  regular-release:
    needs: token-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: deepankarm/_jina
          fetch-depth: 0
      - uses: actions/checkout@v2
        with:
          repository: jina-ai/staging-docs
          path: gh_pages
          token: ${{ secrets.MY_TOKEN }}
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Build doc and push to jina-ai/staging-docs
        run: |
          git checkout -b ${{github.ref }}  # checks out a new branch to avoid `'master' is already checked out at '/home/runner/work/jina/jina'``
          pip install -r requirements.txt
          pip install furo==2021.10.9
          python versionify.py --repodir ${{ github.workspace }} \
            --docsdir ${{ github.workspace }}/gh_pages --commit
          ls -la ${{ github.workspace }}/gh_pages
        working-directory: docs
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
