name: Manual Docs Build (Staging)

on:
  workflow_dispatch:
    inputs:
      release_token:
        description: 'Your release token'
        required: true
      triggered_by:
        description: 'CD | TAG | MANUAL'
        required: false
        default: MANUAL

jobs:
  token-check:
    runs-on: ubuntu-latest
    steps:
      - run: echo "success!"
        if: "${{ github.event.inputs.release_token }} == ${{ env.release_token }}"
        env:
          release_token: ${{ secrets.JINA_CORE_RELEASE_TOKEN }}

  regular-release:
    needs: token-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: deepankarm/_jina
          fetch-depth: 0
      - uses: actions/checkout@v2
        with:
          repository: jina-ai/staging-docs
          path: gh_page
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Build doc and push to jina-ai/staging-docs
        run: |
          git config --local user.email "dev-bot@jina.ai"
          git config --local user.name "Jina Dev Bot"
          pip install -r requirements.txt
          pip install furo==2021.10.9
          
          python versions.py --docs-path ${{ env.GITHUB_WORKSPACE }}/gh_page --commit
          # git status
          # git add docs && git commit -m "chore(docs): update docs due to ${{github.event_name}} on ${{github.repository}}"
          # git push --force origin gh-pages
        working-directory: docs
